name: topeka
description: A fun to play quiz that showcases material design on Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.2
  shared_preferences: ^0.5.12

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  assets:
    - images/avatars/
    - images/categories/
    - images/quizzes/
